name: Run C Code
on:
  push:
    branches:
      - "master"
jobs:
  job1:
    name: Compile the C Code and Give Output
    runs-on: ubuntu-latest
    steps:
      - name: Compile the Code
      - uses: actions/checkout@v2
      - name: Install compiler
      - uses: rlalik/setup-cpp-compiler@v1
        with:
         compiler: latest