name: Run C Code
on:
  push:
    branches:
      - "master"
jobs:
  job1:
    name: Compile the C Code and Give Output
    runs-on: ubuntu-latest
    steps:
      - name: Compile the Code
        run: gcc otp.c
      - name: Run the Code
        run: ./a.exe